createdb -h localhost -p 5432 -U wilq zadanie

crete type type as enum('Furniture', 'Tools', 'Plants');

create table products(
    id serial primary key,
    name text,
    type type,
    price float,
    producer text);

insert into products(name, type, price, producer) values
('Goldenrod', 'Plants', '4', 'Greenland inc'),
('Fern', 'Plants', '3', 'Greenland inc'),
('Bonsai tree', 'Plants', '25', 'Greenland inc'),
('Bamboo', 'Plants', '1.5', 'Greenland inc'),
('Hydrangea', 'Plants', '7', 'Greenland inc'),
('Lavender', 'Plants', '5', 'Greenland inc'),
('Lilac', 'Plants', '6', 'Greenland inc'),
('Datura', 'Plants', '4', 'Greenland inc'),
('Yew tree', 'Plants', '55', 'Greenland inc'),
('Forsythia', 'Plants', '20', 'Greenland inc'),
('Hawthorn', 'Plants', '60', 'Greenland inc'),
('Juniper', 'Plants', '20', 'Greenland inc'),
('Horseradish', 'Plants', '3', 'Veggy Garden'),
('Beetroot', 'Plants', '1', 'Veggy Garden'),
('Onion', 'Plants', '0.5', 'Veggy Garden'),
('Strawberry', 'Plants', '3', 'Sweet&Natural'),
('Blueberry', 'Plants', '5', 'Sweet&Natural'),
('Maple', 'Plants', '80', 'Fever-Tree'),
('Walnut tree', 'Plants', '180', 'Fever-Tree'),
('Spruce', 'Plants', '60', 'Fever-Tree'),
('Steel hammer', 'Tools', '20', 'Bobs Tools'),
('Screwdriwers set', 'Tools', '12', 'Bobs Tools'),
('Chainsaw', 'Tools', '99', 'Stheeel'),
('Shovel', 'Tools', '50', 'Bobs Tools'),
('Pickaxe', 'Tools', '70', 'Bobs Tools'),
('Steel axe', 'Tools', '40', 'Bobs Tools'),
('Saw', 'Tools', '25', 'Bobs Tools'),
('Electric drill', 'Tools', '60', 'Boush'),
('Concrete mixer', 'Tools', '180', 'Bobs Tools'),
('Air compressor', 'Tools', '90', 'Bobs Tools'),
('Barrow', 'Tools', '45', 'ProBuilder'),
('Grinder', 'Tools', '35', 'Boush'),
('Sanitary silicone', 'Tools', '6', 'ProBuilder'),
('Glue', 'Tools', '5', 'ProBuilder'),
('Welder', 'Tools', '30', 'ProBuilder'),
('Construction foam', 'Tools', '4', 'ProBuilder'),
('Nails', 'Tools', '0.5', 'ProBuilder'),
('Crowbar', 'Tools', '16', 'ProBuilder'),
('Pliers', 'Tools', '6', 'Boush'),
('Sofa', 'Furniture', '150', 'Ikea'),
('Chair', 'Furniture', '25', 'Ikea'),
('Futon', 'Furniture', '80', 'Ikea'),
('Table', 'Furniture', '65', 'BlackRedWhite'),
('Cabinet', 'Furniture', '70', 'BlackRedWhite'),
('Bookcase', 'Furniture', '60', 'BlackRedWhite'),
('Dining Table', 'Furniture', '35', 'BlackRedWhite'),
('Bench', 'Furniture', '40', 'BlackRedWhite'),
('Sideboard', 'Furniture', '60', 'BlackRedWhite'),
('Wine Rack', 'Furniture', '200', 'Ikea'),
('Bed', 'Furniture', '545', 'Ikea'),
('Bathroom Stool', 'Furniture', '130', 'Vexon'),
('Kitchen Storage', 'Furniture', '90', 'Vexon'),
('Dressing Table', 'Furniture', '60', 'Vexon'),
('Bedroom Wardrobe', 'Furniture', '400', 'Ikea'),
('Wall Mirror', 'Furniture', '35', 'BlackRedWhite'),
('Wash Stand', 'Furniture', '50', 'Vexon'),
('Shelf', 'Furniture', '40', 'Ikea'),
('Storage Chest', 'Furniture', '75', 'BlackRedWhite');


